/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.time.LocalDate;

/**
 *
 * @author fvr
 */
public class AgendasRealizadas extends javax.swing.JFrame {

    public static String[] zonasV;
    public static String id;
    public static String tipo;
    public static boolean consul = false;

    /**
     * Creates new form ConsultarAgenda
     */
    public AgendasRealizadas() {

        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        setLocationRelativeTo(this);
        frame.setLocationRelativeTo(frame);

    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }
    public DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        valorT = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        frame2 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        valorC = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        concep = new javax.swing.JTextField();
        comentarios = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        comenn = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        comenn1 = new javax.swing.JTextArea();
        Combox1 = new javax.swing.JComboBox<>();
        Combox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelo.addColumn("id");
        modelo.addColumn("fecha/hora instalacion");
        modelo.addColumn("fecha/hora de creacion");
        modelo.addColumn("Zona");
        modelo.addColumn("cliente");
        modelo.addColumn("tecnico");
        modelo.addColumn("estadoC");
        modelo.addColumn("estadoT");
        modelo.addColumn("direccion");
        modelo.addColumn("cedula");
        consultar consul = new consultar();
        jTable2 = new colorcelda();
        formatCC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        TECNICOS = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        buscar = new javax.swing.JTextField();
        por = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();

        frame.setLocationRelativeTo(null);
        frame.setMinimumSize(new java.awt.Dimension(320, 160));
        frame.setResizable(false);

        jLabel2.setText("¿Cuanto se le pagara al tecnico por esta agenda?");

        valorT.setText("0");
        valorT.setToolTipText("0");
        valorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTActionPerformed(evt);
            }
        });

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Rechazar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(frameLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(valorT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        frame2.setLocationRelativeTo(null);
        frame2.setMinimumSize(new java.awt.Dimension(280, 150));
        frame2.setResizable(false);

        jLabel4.setText("Al cliente se le cobrara:");

        valorC.setToolTipText("0");

        jButton8.setText("Aceptar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Crear un nuevo saldo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setText("              por motivo de:");

        concep.setToolTipText("0");

        javax.swing.GroupLayout frame2Layout = new javax.swing.GroupLayout(frame2.getContentPane());
        frame2.getContentPane().setLayout(frame2Layout);
        frame2Layout.setHorizontalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame2Layout.createSequentialGroup()
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(frame2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(concep, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame2Layout.setVerticalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(concep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        comentarios.setMinimumSize(new java.awt.Dimension(330, 380));

        comenn.setEditable(false);
        comenn.setColumns(20);
        comenn.setRows(5);
        jScrollPane1.setViewportView(comenn);

        jLabel3.setText("comentarios de agendadores");

        jLabel6.setText("comentarios de tecnicos");

        comenn1.setEditable(false);
        comenn1.setColumns(20);
        comenn1.setRows(5);
        jScrollPane3.setViewportView(comenn1);

        javax.swing.GroupLayout comentariosLayout = new javax.swing.GroupLayout(comentarios.getContentPane());
        comentarios.getContentPane().setLayout(comentariosLayout);
        comentariosLayout.setHorizontalGroup(
            comentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
            .addGroup(comentariosLayout.createSequentialGroup()
                .addGroup(comentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        comentariosLayout.setVerticalGroup(
            comentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comentariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Combox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "instalaciones", "traslados", "migraciones", "retiros", "soportes","reubicaciones","reinstalacion","plan dual"}));
        Combox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combox1ActionPerformed(evt);
            }
        });

        Combox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombrecliente", "fecha_instalacion", "idtecnico", "zona"}));
        Combox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Combox2MouseClicked(evt);
            }
        });
        Combox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combox2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Buscar en:");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 153, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("ordenar por:");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTable2.setModel(modelo);
        jTable2.setColumnSelectionAllowed(true);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        String []info=new String[10];
        try{

            PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("select * from agendasrealizadas inner join zonas,login,pagos,instalaciones where agendasrealizadas.zona = zonas.id and agendasrealizadas.iddeagenda = pagos.iddeagenda and agendasrealizadas.iddeagenda = instalaciones.id and agendasrealizadas.idtecnico = login.id and agendasrealizadas.tipo = 'instalaciones'");
            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                do{

                    info[0]=rs.getString("agendasrealizadas.iddeagenda");
                    info[1]=rs.getString("agendasrealizadas.fecha_instalacion");
                    info[2]=rs.getString("instalaciones.fecha_instalacion");
                    info[3]=rs.getString("zonas.nombre");
                    info[4]=rs.getString("agendasrealizadas.nombrecliente");
                    info[5]=rs.getString("login.nombre");
                    info[6]=rs.getString("pagos.estadoC");
                    info[7]=rs.getString("pagos.estadoT");
                    info[8]=rs.getString("ubicacion");
                    info[9]=rs.getString("agendasrealizadas.cedula");
                    modelo.addRow(info);

                }while(rs.next());

            }
        }
        catch(Exception e){

        }
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("revise las agendas realizadas por numero de id:");

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ver Datos De La Ejecucion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("  Tecnicos:");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        TECNICOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "todos" }));
        try {

            PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("select * from login order by id asc");
            ResultSet rs = pst.executeQuery();
            int i=0;
            while(rs.next()){
                TECNICOS.addItem(rs.getString("id").toString().trim()+". "+rs.getString("nombre").toString().trim());
                i++;
            }
            rs.first();
            zonasV = new String[i+1];
            i=1;
            zonasV[0]="todos";
            do{

                zonasV[i]=rs.getString("id");
                i++;
            }while(rs.next());

        } catch (Exception e) {

        }
        TECNICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TECNICOSActionPerformed(evt);
            }
        });

        jButton3.setText("Cobrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Aceptar Agenda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("ver solo datos de este mes");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });

        por.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "cedula", "ID","direccion"}));
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });

        jButton7.setText("Exportar Datos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formatCC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jButton1)))))
                .addGap(22, 22, 22))
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TECNICOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TECNICOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combox1ActionPerformed
        Ordenar ordena = new Ordenar();
        tipo = Combox1.getSelectedItem().toString().trim();
        try {
            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        } catch (Exception e) {

        }

        ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                Combox2.getSelectedItem().toString().trim(),
                zonasV[TECNICOS.getSelectedIndex()], modelo);

    }//GEN-LAST:event_Combox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Combox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combox2ActionPerformed
        Ordenar ordena = new Ordenar();
        tipo = Combox1.getSelectedItem().toString().trim();
        try {
            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        } catch (Exception e) {

        }

        ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                Combox2.getSelectedItem().toString().trim(),
                zonasV[TECNICOS.getSelectedIndex()], modelo);


    }//GEN-LAST:event_Combox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.id = formatCC.getText();
        this.tipo = Combox1.getSelectedItem().toString().trim();
        formatCC.setText("");
        consultar consultar1 = new consultar();
        if (consultar1.devolver(id, Combox1.getSelectedItem().toString().trim(), "") == null) {
            JOptionPane.showMessageDialog(null, "no se encontro la agenda");
        } else {

            VerEjecutadas inst = new VerEjecutadas();
            inst.setVisible(true);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void Combox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Combox2MouseClicked

    }//GEN-LAST:event_Combox2MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 2) {
            int seleccionar = jTable2.rowAtPoint(evt.getPoint());
            consultar consul = new consultar();

            int seleccionar1 = jTable2.columnAtPoint(evt.getPoint());
            String[] info = consul.devolver(jTable2.getValueAt(seleccionar, 0).toString(), Combox1.getSelectedItem().toString());
            String[] info1 = consul.devolver(jTable2.getValueAt(seleccionar, 0).toString(), Combox1.getSelectedItem().toString(), "");
            formatCC.setText(String.valueOf(jTable2.getValueAt(seleccionar, 0)));
            Toolkit.getDefaultToolkit()
                    .getSystemClipboard()
                    .setContents(
                            new StringSelection(String.valueOf(jTable2.getValueAt(seleccionar, seleccionar1))),
                            null
                    );
            comentarios.setVisible(true);
            comenn.setText(info[4]);
            comenn1.setText(info1[0]);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio ins = new Inicio();
        ins.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void TECNICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TECNICOSActionPerformed
        Ordenar ordena = new Ordenar();
        tipo = Combox1.getSelectedItem().toString().trim();

        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                Combox2.getSelectedItem().toString().trim(),
                zonasV[TECNICOS.getSelectedIndex()], modelo);
    }//GEN-LAST:event_TECNICOSActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        consultar consultar1 = new consultar();
        String[] cliente = consultar1.devolver(formatCC.getText(), Combox1.getSelectedItem().toString().trim(), "");

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "no se encontro la agenda");
            frame.setVisible(false);

        } else {
            if (cliente[12].equals("sin pagar")) {
                valorT.setText(cliente[10]);
                frame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "la agenda ya fue pagada al tecnico");
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        consultar consultar1 = new consultar();
        String[] cliente = consultar1.devolver(formatCC.getText(), Combox1.getSelectedItem().toString().trim(), "");

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "no se encontro la agenda");
            frame2.setVisible(false);

        } else {
            if (cliente[11].equals("sin cobrar")) {
                valorC.setText(cliente[9]);
                frame2.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "la agenda ya fue cobrada al cliente");
                valorC.setText(cliente[9]);
                frame2.setVisible(true);
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Ordenar ordena = new Ordenar();
        String[] info = ordena.OrdenarEJ(formatCC.getText().trim());
        try {
            PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("update pagos set estadoT = ?, valortecnico = ? where iddeagenda = ?");
            pst.setString(3, formatCC.getText().trim());
            pst.setString(1, "aceptada");
            pst.setString(2, valorT.getText().trim());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "aceptada");

            frame.setVisible(false);
            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                    Combox2.getSelectedItem().toString().trim(),
                    zonasV[TECNICOS.getSelectedIndex()], modelo);
            try {

                URL uri = new URL("https://internet2.fututel.com/html/agenda/enviaremail.php?nombre=" + info[1].replace(" ", "%20") + "&agendador=" + IniciarSession.NombreInicio.replace(" ", "%20") + "&correo=" + info[2].replace(" ", "%20") + "&cliente=" + info[3].replace(" ", "%20") + "&tipo=" + info[4].replace(" ", "%20") + "&iddeagenda=" + info[0].replace(" ", "%20") + "&estado=" + "aceptado" + "&valor=" + info[6].replace(" ", "%20") + "");
                URLConnection mail = uri.openConnection();
                BufferedReader in = new BufferedReader(
                        new InputStreamReader(
                                mail.getInputStream()));
                String inputLine;

                while ((inputLine = in.readLine()) != null) {
                }
                in.close();
            } catch (Exception e) {
            }
            formatCC.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        frame2.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Ordenar ordena = new Ordenar();
        consultar consultar1 = new consultar();
        String[] cliente = consultar1.devolver(formatCC.getText(), Combox1.getSelectedItem().toString().trim());
        String concepto = concep.getText().trim();
        if (concepto.equals("")) {
            concepto = "generado desde la app de agendas";
        }
        try {
            PreparedStatement pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("insert into saldos values(?,?,?,?,?,?,?,?,'')");
            pst.setString(1, "0");
            pst.setString(2, cliente[11]);
            pst.setString(3, "00000000");
            pst.setString(4, "00000000");
            pst.setString(5, "no cobrado");
            pst.setString(6, valorC.getText());
            pst.setString(7, LocalDate.now().toString());
            pst.setString(8, concepto);
            pst.execute();
            pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("update pagos set fecha_cobro = ?, estadoC = ? where iddeagenda = ?");
            pst.setString(3, formatCC.getText().trim());
            pst.setString(1, LocalDate.now().toString());
            pst.setString(2, "cobrado");
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "agenda cobrada");
            formatCC.setText("");
            frame2.setVisible(false);
            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                    Combox2.getSelectedItem().toString().trim(),
                    zonasV[TECNICOS.getSelectedIndex()], modelo);
        } catch (Exception e) {
           System.out.println(e);
        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void valorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Ordenar ordena = new Ordenar();
        String[] info = ordena.OrdenarEJ(formatCC.getText().trim());
        try {
            PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("update pagos set estadoT = ? where iddeagenda = ?");
            pst.setString(2, formatCC.getText().trim());
            pst.setString(1, "rechazada");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "rechazada");
            try {

                URL uri = new URL("https://internet2.fututel.com/html/agenda/enviaremail.php?nombre=" + info[1].replace(" ", "%20") + "&agendador=" + IniciarSession.NombreInicio.replace(" ", "%20") + "&correo=" + info[2].replace(" ", "%20") + "&cliente=" + info[3].replace(" ", "%20") + "&tipo=" + info[4].replace(" ", "%20") + "&iddeagenda=" + info[0].replace(" ", "%20") + "&estado=" + "rechazado" + "&valor=" + info[6].replace(" ", "%20") + "");
                URLConnection mail = uri.openConnection();
                BufferedReader in = new BufferedReader(
                        new InputStreamReader(
                                mail.getInputStream()));
                String inputLine;

                while ((inputLine = in.readLine()) != null) {
                }
                in.close();
            } catch (Exception e) {
            }
            formatCC.setText("");
            frame.setVisible(false);
            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                    Combox2.getSelectedItem().toString().trim(),
                    zonasV[TECNICOS.getSelectedIndex()], modelo);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Ordenar ordena = new Ordenar();
        if (jCheckBox1.isSelected()) {

            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                    Combox2.getSelectedItem().toString().trim(),
                    zonasV[TECNICOS.getSelectedIndex()], modelo, "");

        } else {

            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            ordena.OrdenarEJ(Combox1.getSelectedItem().toString().trim(),
                    Combox2.getSelectedItem().toString().trim(),
                    zonasV[TECNICOS.getSelectedIndex()], modelo);

        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped


    }//GEN-LAST:event_buscarKeyTyped

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            Ordenar ordena = new Ordenar();
            String opcion;
            switch (por.getSelectedItem().toString()) {
                case "cedula":
                    opcion = "agendasrealizadas.cedula";
                    break;
                case "direccion":
                    opcion = "agendasrealizadas.ubicacion";
                    break;
                case "nombre":

                    opcion = "agendasrealizadas.nombrecliente";

                    break;
                case "ID":

                    if (Combox1.getSelectedItem().toString().trim().equals("instalaciones")) {
                        opcion = "instalaciones.id";
                    } else {
                        opcion = "agendasvarias.id";
                    }

                    break;
                default:
                    opcion = "agendasrealizadas.nombrecliente";
                    break;

            }
            if (jCheckBox1.isSelected()) {

                for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                }
                ordena.OrdenarEJ(opcion, buscar.getText().trim(), Combox1.getSelectedItem().toString().trim(),
                        Combox2.getSelectedItem().toString().trim(),
                        zonasV[TECNICOS.getSelectedIndex()], modelo, "");

            } else {

                for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                    modelo.removeRow(i);
                }
                ordena.OrdenarEJ(opcion, buscar.getText().trim(), Combox1.getSelectedItem().toString().trim(),
                        Combox2.getSelectedItem().toString().trim(),
                        zonasV[TECNICOS.getSelectedIndex()], modelo);

            }
        }
    }//GEN-LAST:event_buscarKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendasRealizadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combox1;
    private javax.swing.JComboBox<String> Combox2;
    private javax.swing.JComboBox<String> TECNICOS;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextArea comenn;
    private javax.swing.JTextArea comenn1;
    private javax.swing.JFrame comentarios;
    private javax.swing.JTextField concep;
    private javax.swing.JTextField formatCC;
    private javax.swing.JFrame frame;
    private javax.swing.JFrame frame2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> por;
    private javax.swing.JTextField valorC;
    private javax.swing.JTextField valorT;
    // End of variables declaration//GEN-END:variables
}
