/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;



import clases.Ordenar;
import clases.consultar;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bvr217
 */
public class agendasvarias extends javax.swing.JFrame {
    public DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };
    boolean consultarA = ConsultarAgenda.consul;
    String id;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    String date = dtf.format(LocalDateTime.now());

    /**
     * Creates new form agendasvarias
     */
    public agendasvarias() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        jButton1.setEnabled(false);
        setLocationRelativeTo(this);
        String[] datosReturn = new String[5];

        String consultarB = ConsultarAgenda.id;
        String consultartipo = ConsultarAgenda.tipo;
        String[] datosReturnConsul = new String[13];

        if (consultarA) {
            try {
                id = ConsultarAgenda.id;
                jButton1.setText("EDITAR");
                consultar consultar1 = new consultar();
                datosReturnConsul = consultar1.devolver(consultarB, consultartipo);
                int año = Integer.parseInt(datosReturnConsul[0].substring(0, 4));
                int mes = Integer.parseInt(datosReturnConsul[0].substring(5, 7)) - 1;
                int dia = Integer.parseInt(datosReturnConsul[0].substring(8, 10));

                Calendar calen = new GregorianCalendar(año, mes, dia);

                idC.setText(datosReturnConsul[11]);
                Ordenar orden = new Ordenar();
                orden.Consultar(id, modelo);
                tipoA.setSelectedItem(datosReturnConsul[12]);
                coment.setText(datosReturnConsul[4]);
                datosReturn = consultar1.devolverU(datosReturnConsul[6]);
                User.setText(datosReturn[0]);
                ASIGNADO.setText(datosReturnConsul[7]);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            //aqui va el usuariooooo
        } else {
            User.setText(IniciarSession.NombreInicio);
        }
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JTextField();
        Nombre_txt = new javax.swing.JTextField();
        Nombre_txt1 = new javax.swing.JTextField();
        Nombre_txt2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        coment = new javax.swing.JTextArea();
        idC = new javax.swing.JTextField();
        tipoA = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        User = new javax.swing.JLabel();
        ASIGNADO = new javax.swing.JLabel();
        Nombre_txt4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Nombre_txt5 = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Titulo.setEditable(false);
        Titulo.setBackground(new java.awt.Color(0, 153, 0));
        Titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("  AGREGAR AGENDA ");
        Titulo.setBorder(null);
        Titulo.setName(""); // NOI18N
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });

        Nombre_txt.setEditable(false);
        Nombre_txt.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt.setText(" ID del cliente:");
        Nombre_txt.setToolTipText("");
        Nombre_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txtActionPerformed(evt);
            }
        });

        Nombre_txt1.setEditable(false);
        Nombre_txt1.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt1.setText(" tipo de agenda:");
        Nombre_txt1.setToolTipText("");
        Nombre_txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt1ActionPerformed(evt);
            }
        });

        Nombre_txt2.setEditable(false);
        Nombre_txt2.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt2.setText("  comentarios:");
        Nombre_txt2.setToolTipText("");
        Nombre_txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt2ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        coment.setColumns(20);
        coment.setRows(5);
        coment.setPreferredSize(new java.awt.Dimension(300, 0));
        jScrollPane1.setViewportView(coment);

        idC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idCMouseClicked(evt);
            }
        });
        idC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCActionPerformed(evt);
            }
        });

        tipoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "soportes", "retiros", "traslados", "migraciones","reubicaciones","reinstalacion","plan dual" }));
        tipoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGENDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("comprobar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 153, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(240, 240, 240));
        jTextField4.setText(" AGENDADO POR:");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(240, 240, 240));
        jTextField3.setText("        ASIGNADO A:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        User.setText("agend user");

        Nombre_txt4.setEditable(false);
        Nombre_txt4.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt4.setText("  Tipo de cable:");
        Nombre_txt4.setToolTipText("");
        Nombre_txt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UTP", "FIBRA OPTICA", "ANTENA"}));
        jComboBox1.setPreferredSize(new java.awt.Dimension(60, 20));

        Nombre_txt5.setEditable(false);
        Nombre_txt5.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt5.setText("  precio:");
        Nombre_txt5.setToolTipText("");
        Nombre_txt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt5ActionPerformed(evt);
            }
        });

        precio.setText("0");

        jTable1.setModel(modelo);
        modelo.addColumn("fecha/hora");
        modelo.addColumn("estado");
        modelo.addColumn("tecnico");
        jTable1.setModel(modelo);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ASIGNADO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nombre_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre_txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(Nombre_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_txt4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ASIGNADO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Nombre_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt1ActionPerformed

    private void Nombre_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] info = new String[5];
        String[] infoC = new String[6];
        consultar consul = new consultar();
        if (consultarA) {
            try {

                PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("update agendasvarias set idcliente = ?, tipo = ?, comentarios = ?,  fecha_instalacion= ?,valor = ? where id = ?");

                //aqui ponemos el usuario que agendo
                if (coment.getText().trim().length() < 2) {
                    pst.setString(1, idC.getText().trim());
                    pst.setString(2, tipoA.getSelectedItem().toString().trim());
                    pst.setString(3, coment.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                    pst.setString(4, date);
                    pst.setString(5, precio.getText().trim());
                    pst.setString(6, id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "registrado para " + tipoA.getSelectedItem().toString().trim() + " el " + date.trim());

                    this.dispose();
                } else {
                    pst.setString(1, idC.getText().trim());
                    pst.setString(2, tipoA.getSelectedItem().toString().trim());
                    pst.setString(3, coment.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                    pst.setString(4, date);
                    pst.setString(5, precio.getText().trim());
                    pst.setString(6, id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "registrado para " + tipoA.getSelectedItem().toString().trim() + " el " + date.trim());

                    this.dispose();
                }

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "servidor desconectado, intente reiniciar la conexion " + e);
            }
        } else {
            try {

                PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("insert into agendasvarias values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

                if (coment.getText().trim().length() < 2) {
                    pst.setString(1, "0");
                    pst.setString(2, idC.getText().trim());
                    pst.setString(3, tipoA.getSelectedItem().toString().trim());
                    pst.setString(4, coment.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                    info = consul.devolverU(IniciarSession.Username, "todos");
                    pst.setString(5, info[4]);
                    pst.setString(6, "0");
                    pst.setString(7, "PENDIENTE");
                    pst.setString(8, date);
                    infoC = consul.devolverC(idC.getText().trim());
                    pst.setString(9, infoC[5]);
                    pst.setString(10, infoC[0]);
                    pst.setString(11, infoC[1]);
                    try {
                        Integer.parseInt(infoC[3]);
                    } catch (Exception e) {
                        infoC[3] = "0";
                        JOptionPane.showMessageDialog(null, "¡el cliente seleccionado no tiene un numero de cedula!");
                    }
                    pst.setString(12, infoC[3]);
                    pst.setString(13, infoC[2]);
                    pst.setString(14, "1000-01-01");
                    pst.setString(15, precio.getText().trim());
                    pst.setString(16, "");

                    pst.execute();
                    JOptionPane.showMessageDialog(null, "registrado para " + tipoA.getSelectedItem().toString().trim() + " el " + date.trim());

                    this.dispose();

                    this.dispose();
                } else {
                    pst.setString(1, "0");
                    pst.setString(2, idC.getText().trim());
                    pst.setString(3, tipoA.getSelectedItem().toString().trim());
                    pst.setString(4, coment.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                    info = consul.devolverU(IniciarSession.Username, "todos");
                    pst.setString(5, info[4]);
                    pst.setString(6, "0");
                    pst.setString(7, "PENDIENTE");
                    pst.setString(8, date);
                    infoC = consul.devolverC(idC.getText().trim());
                    pst.setString(9, infoC[5]);
                    pst.setString(10, infoC[0]);
                    pst.setString(11, infoC[1]);
                    try {
                        Integer.parseInt(infoC[3]);
                    } catch (Exception e) {
                        infoC[3] = "0";
                        JOptionPane.showMessageDialog(null, "¡el cliente seleccionado no tiene un numero de cedula!");
                    }

                    pst.setString(12, infoC[3]);
                    pst.setString(13, infoC[2]);
                    pst.setString(14, "1000-01-01");
                    pst.setString(15, precio.getText().trim());
                    pst.setString(16, "");
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "registrado para " + tipoA.getSelectedItem().toString().trim() + " el " + date.trim());

                    this.dispose();

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "servidor desconectado, intente reiniciar la conexion " + e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String[] cliente;
        consultar consul = new consultar();
        if (idC.getText().trim().length() >= 1) {
            cliente = consul.devolverC(idC.getText().trim());

            if (cliente != null) {

                if (cliente[6].equals("RETIRADO")) {
                    tipoA.setSelectedItem("reinstalacion");
                    tipoA.disable();
                } else {
                    tipoA.setEnabled(true);
                    tipoA.setSelectedItem("soportes");

                }
                JOptionPane.showMessageDialog(null, cliente[0] + "\n" + cliente[1] + "\n" + cliente[2] + "\n" + cliente[3] + "\n" + cliente[4] + "\n");
                jButton1.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "el cliente no existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "no hay nada que comprobar");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void idCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCActionPerformed

    }//GEN-LAST:event_idCActionPerformed

    private void idCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idCMouseClicked
        jButton1.setEnabled(false);
    }//GEN-LAST:event_idCMouseClicked

    private void tipoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAActionPerformed

    private void Nombre_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt4ActionPerformed

    private void Nombre_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendasvarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendasvarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendasvarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendasvarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendasvarias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASIGNADO;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField Nombre_txt1;
    private javax.swing.JTextField Nombre_txt2;
    private javax.swing.JTextField Nombre_txt4;
    private javax.swing.JTextField Nombre_txt5;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel User;
    private javax.swing.JTextArea coment;
    private javax.swing.JTextField idC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox<String> tipoA;
    // End of variables declaration//GEN-END:variables
}
