/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import clases.*;
import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fvr
 */
public class AgregarActa extends javax.swing.JFrame {
    public DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };

    private String privilege;
    public static String[] zonasV;
    String[] datosReturn = new String[5];
    private LocalDate fechaA = LocalDate.now();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    String fechaa = dtf.format(LocalDateTime.now());
    String id;
    /**
     * Creates new form AgregarActa
     */
    private boolean b = false, c = false, d = false, e = false, f = false, g = false, editado = false;

    public AgregarActa() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        privilege = IniciarSession.privilege;
        if (privilege.equals("0")) {
            Nombre_txt6.setVisible(true);
            Azona.setVisible(true);
            Nombre_txt5.setVisible(true);
            idZona.setVisible(true);
            jButton3.setVisible(true);

        } else {
            Nombre_txt6.setVisible(false);
            Azona.setVisible(false);
            Nombre_txt5.setVisible(false);
            idZona.setVisible(false);
            jButton3.setVisible(false);

        }
        User.setText(IniciarSession.NombreInicio);
        DATE.setPreferredSize(new java.awt.Dimension(97, 22));
        boolean consultarA = ConsultarAgenda.consul;
        String consultarB = ConsultarAgenda.id;
        String[] datosReturnConsul = new String[13];

        if (consultarA) {
            id = ConsultarAgenda.id;
            jButton1.setText("EDITAR");
            b = true;
            c = true;
            d = true;
            e = true;
            g = true;
            consultar consultar1 = new consultar();
            datosReturnConsul = consultar1.devolver(consultarB, "instalaciones");
            Ordenar orden = new Ordenar();
            orden.Consultar(id, modelo);
            int año = Integer.parseInt(datosReturnConsul[0].substring(0, 4));
            int mes = Integer.parseInt(datosReturnConsul[0].substring(5, 7)) - 1;
            int dia = Integer.parseInt(datosReturnConsul[0].substring(8, 10));

            Calendar calen = new GregorianCalendar(año, mes, dia);
            DATE.setDate(calen.getTime());
            NOMBRE.setText(datosReturnConsul[1]);
            CC.setText(datosReturnConsul[2]);
            CELULAR.setText(datosReturnConsul[3]);
            COMENT.setText(datosReturnConsul[4]);
            DIRECCION.setText(datosReturnConsul[5]);
            datosReturn = consultar1.devolverU(datosReturnConsul[6]);
            User.setText(datosReturn[0]);
            ASIGNADO.setText(datosReturnConsul[7]);
            zonas.setSelectedIndex(Integer.parseInt(datosReturnConsul[9]));
            editado = true;

            //aqui va el usuariooooo
        }

        setLocationRelativeTo(this);

    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        CELULAR = new javax.swing.JTextField();
        DIRECCION = new javax.swing.JTextField();
        Nombre_txt = new javax.swing.JTextField();
        Nombre_txt1 = new javax.swing.JTextField();
        Nombre_txt2 = new javax.swing.JTextField();
        Nombre_txt3 = new javax.swing.JTextField();
        Nombre_txt4 = new javax.swing.JTextField();
        zonas = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        COMENT = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        DATE = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        ASIGNADO = new javax.swing.JLabel();
        Nombre_txt5 = new javax.swing.JTextField();
        Azona = new javax.swing.JTextField();
        Nombre_txt6 = new javax.swing.JTextField();
        idZona = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Nombre_txt7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Nombre_txt8 = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 704, 550));
        setMinimumSize(new java.awt.Dimension(705, 550));
        setPreferredSize(new java.awt.Dimension(728, 810));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setEditable(false);
        Titulo.setBackground(new java.awt.Color(0, 153, 0));
        Titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText(" AGENDA DE INSTALACIONES");
        Titulo.setBorder(null);
        Titulo.setName(""); // NOI18N
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 57, 290, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("     FECHA PARA INSTALACION");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 132, 215, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 153, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(240, 240, 240));
        jTextField2.setText("                                              DATOS DEL CLIENTE TITULAR");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 173, 596, -1));

        CC.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CCMouseClicked(evt);
            }
        });
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        getContentPane().add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 376, -1));

        CELULAR.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CELULAR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CELULAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CELULARMouseClicked(evt);
            }
        });
        getContentPane().add(CELULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 376, -1));

        DIRECCION.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        DIRECCION.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DIRECCION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DIRECCIONMouseClicked(evt);
            }
        });
        getContentPane().add(DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 376, -1));

        Nombre_txt.setEditable(false);
        Nombre_txt.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt.setText("             Nombres y Apellidos:");
        Nombre_txt.setToolTipText("");
        Nombre_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 201, 213, -1));

        Nombre_txt1.setEditable(false);
        Nombre_txt1.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt1.setText("                            No.Cédula:");
        Nombre_txt1.setToolTipText("");
        Nombre_txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 213, -1));

        Nombre_txt2.setEditable(false);
        Nombre_txt2.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt2.setText("                            No.Celular:");
        Nombre_txt2.setToolTipText("");
        Nombre_txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 213, -1));

        Nombre_txt3.setEditable(false);
        Nombre_txt3.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt3.setText("                             Direccion:");
        Nombre_txt3.setToolTipText("");
        Nombre_txt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt3ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 213, -1));

        Nombre_txt4.setEditable(false);
        Nombre_txt4.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt4.setText("  Tipo de cable:");
        Nombre_txt4.setToolTipText("");
        Nombre_txt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt4ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 100, -1));

        zonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        zonas.setPreferredSize(new java.awt.Dimension(100, 20));
        try {

            int i=0;
            PreparedStatement pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("select count(*) from zonas order by id asc");
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                i=Integer.parseInt(rs.getString("count(*)"));
            }

            zonasV = new String[i];
            pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("select * from zonas order by id asc");
            rs = pst.executeQuery();
            i=0;
            while(rs.next()){
                zonas.addItem(rs.getString("id").toString().trim()+". "+rs.getString("zona").toString().trim());
                zonasV[i]=rs.getString("id");
                i++;

            }

        } catch (Exception e) {

        }
        zonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonasActionPerformed(evt);
            }
        });
        getContentPane().add(zonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(240, 240, 240));
        jTextField3.setText("                            ASIGNADO A:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 215, -1));

        jScrollPane3.setViewportView(COMENT);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 590, 76));

        jLabel1.setText("comentarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        NOMBRE.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        NOMBRE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NOMBRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOMBREMouseClicked(evt);
            }
        });
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 201, 376, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGENDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, -1, -1));

        User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        User.setText("agend user");
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 223, 20));

        DATE.setDateFormatString("yyyy-MM-dd");
        DATE.setDoubleBuffered(false);
        getContentPane().add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 133, 250, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 153, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(240, 240, 240));
        jTextField4.setText("                     AGENDADO POR:");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 215, -1));
        getContentPane().add(ASIGNADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 180, 20));

        Nombre_txt5.setEditable(false);
        Nombre_txt5.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt5.setText(" ID zona:");
        Nombre_txt5.setToolTipText("");
        Nombre_txt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt5ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, -1));
        getContentPane().add(Azona, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 120, -1));

        Nombre_txt6.setEditable(false);
        Nombre_txt6.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt6.setText("  Precio:");
        Nombre_txt6.setToolTipText("");
        Nombre_txt6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt6.setMaximumSize(new java.awt.Dimension(92, 21));
        Nombre_txt6.setPreferredSize(new java.awt.Dimension(58, 21));
        Nombre_txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt6ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 90, -1));
        getContentPane().add(idZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 30, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AGREGAR ZONA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 347, -1, -1));

        Nombre_txt7.setEditable(false);
        Nombre_txt7.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt7.setText("  Zona:");
        Nombre_txt7.setToolTipText("");
        Nombre_txt7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt7ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 80, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UTP", "FIBRA OPTICA", "ANTENA"}));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        Nombre_txt8.setEditable(false);
        Nombre_txt8.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt8.setText("  Nueva Zona:");
        Nombre_txt8.setToolTipText("");
        Nombre_txt8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt8.setMaximumSize(new java.awt.Dimension(92, 21));
        Nombre_txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt8ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        precio.setText("0");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel());
        modelo.addColumn("fecha/hora");
        modelo.addColumn("estado");
        modelo.addColumn("tecnico");
        modelo.addColumn("actor");
        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 590, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Nombre_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt1ActionPerformed

    private void Nombre_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt2ActionPerformed

    private void Nombre_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt3ActionPerformed

    private void Nombre_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt4ActionPerformed

    private void CCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCMouseClicked

        if (!b) {
            CC.setText("");
            CC.setFont(new Font("Arial", Font.PLAIN, 14));
            CC.setBorder(BorderFactory.createEtchedBorder());
        }
        b = true; // TODO add your handling code here:
    }//GEN-LAST:event_CCMouseClicked

    private void CELULARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CELULARMouseClicked
        // TODO add your handling code here:
        if (!c) {
            CELULAR.setText("");
            CELULAR.setFont(new Font("Arial", Font.PLAIN, 14));
            CELULAR.setBorder(BorderFactory.createEtchedBorder());
        }
        c = true;
    }//GEN-LAST:event_CELULARMouseClicked

    private void DIRECCIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIRECCIONMouseClicked

        if (!d) {
            DIRECCION.setText("");
            DIRECCION.setFont(new Font("Arial", Font.PLAIN, 14));
            DIRECCION.setBorder(BorderFactory.createEtchedBorder());
        }
        d = true;// TODO add your handling code here:
    }//GEN-LAST:event_DIRECCIONMouseClicked

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void NOMBREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOMBREMouseClicked

        if (!g) {
            NOMBRE.setText("");
            NOMBRE.setFont(new Font("Arial", Font.PLAIN, 14));
            NOMBRE.setBorder(BorderFactory.createEtchedBorder());
        }
        g = true;// TODO add your handling code here:
    }//GEN-LAST:event_NOMBREMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultar consul = new consultar();
        String[] info = new String[5];
        if (editado) {
            String date = "";
            String ano = "";
            String mes = "";
            try {
                PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("update instalaciones set cliente = ?, direccion = ?,movil = ?, zona = ?, notas = ?, cedula = ?, fecha_instalacion = ?, valor = ? WHERE id = ? ");
                PreparedStatement pst1 = mantenerConexion.conectando.getconec1().getcn().prepareStatement("update instalaciones set cliente = ?, direccion = ?,movil = ?, zona = ?, notas = ?, cedula = ?, fecha_instalacion = ? WHERE id = ? ");
                //aqui ponemos el usuario que agendo
                ValidadorFecha valid = new ValidadorFecha();
                boolean fecha = false;
                try {
                    ano = DATE.getCalendar().get(Calendar.YEAR) + "-";
                    mes = "";
                    switch (DATE.getCalendar().get(Calendar.MONTH)) {
                        case 10:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        case 9:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        case 11:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        default:
                            mes = "0" + (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                    }
                    if (DATE.getCalendar().get(Calendar.DAY_OF_MONTH) < 9) {
                        date = ano + mes + "0" + DATE.getCalendar().get(Calendar.DAY_OF_MONTH);
                    } else {
                        date = ano + mes + DATE.getCalendar().get(Calendar.DAY_OF_MONTH);
                    }
                } catch (Exception e) {

                }

                fecha = valid.validar(date.trim());
                if (!fecha) {
                    JOptionPane.showMessageDialog(null, "formato de fecha invalido");
                    DATE.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));

                } else {
                    if (NOMBRE.getText().trim().length() < 10) {
                        JOptionPane.showMessageDialog(null, "ingrese un nombre de usuaio con su apellido");
                        NOMBRE.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                        g = false;
                    } else {
                        if (CC.getText().trim().length() < 7 || date.trim().length() > 11) {
                            JOptionPane.showMessageDialog(null, "ingrese un numero de cedula.");
                            CC.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                            b = false;
                        } else {
                            String[] cliente = consul.devolverCC(CC.getText().trim());
                            if(cliente != null){
                                JOptionPane.showMessageDialog(null, "el usuario con esa cedula ya existe \nsu nombre: " + cliente[0] + "\nestado: "+cliente[6]);
                            } else{
                                if (CELULAR.getText().trim().length() < 10) {
                                    JOptionPane.showMessageDialog(null, "ingrese almenos un numero de celular");
                                    CELULAR.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                                    c = false;
                                } else {
                                    if (DIRECCION.getText().trim().length() < 1) {
                                        JOptionPane.showMessageDialog(null, "ingrese una direccion");
                                        DIRECCION.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                                        d = false;
                                    } else {

                                        pst1.setString(1, NOMBRE.getText().trim());
                                        pst1.setString(2, DIRECCION.getText().trim());
                                        pst1.setString(3, CELULAR.getText().trim());
                                        pst1.setString(4, zonasV[zonas.getSelectedIndex()]);
                                        pst1.setString(5, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                        pst1.setString(6, CC.getText().trim());
                                        pst1.setString(7, date.trim());
                                        pst1.setString(8, id);
                                        pst.setString(1, NOMBRE.getText().trim());
                                        pst.setString(2, DIRECCION.getText().trim());
                                        pst.setString(3, CELULAR.getText().trim());
                                        pst.setString(4, zonasV[zonas.getSelectedIndex()]);
                                        pst.setString(5, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                        pst.setString(6, CC.getText().trim());
                                        pst.setString(7, date.trim());
                                        pst.setString(9, id);
                                        pst.setString(8, precio.getText().trim());

                                        pst1.executeUpdate();
                                        pst.executeUpdate();
                                        JOptionPane.showMessageDialog(null, "editado exitoso");
                                        ConsultarAgenda.consul = false;
                                        this.dispose();

                                    }
                                }
                            }
                        }
                    }
                }

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, "servidor desconectado, intente reiniciar la conexion" + e);
            } catch (HeadlessException a) {
            }
        } else {
            String date = "";
            String ano = "";
            String mes = "";
            try {
                PreparedStatement pst = mantenerConexion.conectando.getconec2().getcn().prepareStatement("insert into instalaciones values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                PreparedStatement pst1 = mantenerConexion.conectando.getconec1().getcn().prepareStatement("insert into instalaciones values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                //aqui ponemos el usuario que agendo
                ValidadorFecha valid = new ValidadorFecha();
                boolean fecha = false;
                try {
                    ano = DATE.getCalendar().get(Calendar.YEAR) + "-";
                    mes = "";
                    switch (DATE.getCalendar().get(Calendar.MONTH)) {
                        case 10:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        case 9:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        case 11:
                            mes = (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                        default:
                            mes = "0" + (DATE.getCalendar().get(Calendar.MONTH) + 1) + "-";
                            break;
                    }
                    if (DATE.getCalendar().get(Calendar.DAY_OF_MONTH) <= 9) {
                        date = ano + mes + "0" + DATE.getCalendar().get(Calendar.DAY_OF_MONTH);
                    } else {
                        date = ano + mes + DATE.getCalendar().get(Calendar.DAY_OF_MONTH);
                    }
                } catch (Exception e) {

                }
                fecha = valid.validar(date);

                if (!fecha) {
                    JOptionPane.showMessageDialog(null, "formato de fecha invalido");
                    DATE.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));

                } else {
                    if (NOMBRE.getText().trim().length() < 10) {
                        JOptionPane.showMessageDialog(null, "ingrese un nombre de usuaio con su apellido");
                        NOMBRE.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                        g = false;
                    } else {
                        if (CC.getText().trim().length() < 7 || date.trim().length() > 11) {
                            JOptionPane.showMessageDialog(null, "ingrese un numero de cedula");
                            CC.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                            b = false;
                        } else {
                            String[] cliente = consul.devolverCC(CC.getText().trim());
                            if(cliente != null){
                                JOptionPane.showMessageDialog(null, "el usuario con esa cedula ya existe \nsu nombre: " + cliente[0] + "\nestado: "+cliente[6]);
                            } else{
                                if (CELULAR.getText().trim().length() < 10) {
                                    JOptionPane.showMessageDialog(null, "ingrese almenos un numero de celular");
                                    CELULAR.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                                    c = false;
                                } else {
                                    if (DIRECCION.getText().trim().length() < 1) {
                                        JOptionPane.showMessageDialog(null, "ingrese una direccion");
                                        DIRECCION.setBorder(BorderFactory.createMatteBorder(1, 4, 1, 4, Color.RED));
                                        d = false;
                                    } else {

                                        if (COMENT.getText().trim().length() < 2) {
                                            pst.setString(1, "0");
                                            pst.setString(2, DIRECCION.getText().trim());
                                            pst.setString(3, CELULAR.getText().trim());
                                            pst.setString(4, CC.getText().trim());
                                            pst.setString(5, "PENDIENTE");
                                            pst.setString(6, NOMBRE.getText().trim());
                                            pst.setString(7, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                            pst.setString(8, valid.Devolver(date.trim()));
                                            pst.setString(9, zonasV[zonas.getSelectedIndex()]);
                                            info = consul.devolverU(IniciarSession.Username, "todos");
                                            pst.setString(10, info[4]);
                                            pst.setString(11, "0");
                                            pst.setString(12, "1000-01-01");
                                            pst.setString(13, precio.getText().trim());
                                            pst.setString(14, fechaa);

                                            pst1.setString(1, "0");
                                            pst1.setString(2, "000000");
                                            pst1.setString(3, fechaA.toString());//CAMBIAR
                                            pst1.setString(4, "0000-00-00");
                                            pst1.setString(5, "0");
                                            pst1.setString(6, DIRECCION.getText().trim());
                                            pst1.setString(7, "");
                                            pst1.setString(8, CELULAR.getText().trim());
                                            pst1.setString(9, "0");
                                            pst1.setString(10, "");
                                            pst1.setString(11, CC.getText().trim());
                                            pst1.setString(12, "PENDIENTE");
                                            pst1.setString(13, NOMBRE.getText().trim());
                                            pst1.setString(14, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                            pst1.setString(15, valid.Devolver(date.trim()));
                                            pst1.setString(16, zonasV[zonas.getSelectedIndex()]);
                                            pst1.setString(17, "");
                                            pst1.setString(18, info[4]);
                                            pst1.setString(19, "");
                                            pst1.setString(20, "");
                                            pst1.setString(21, "");
                                            pst1.setString(22, "");
                                            pst1.setString(23, "");

                                            pst1.execute();
                                            pst.execute();
                                            JOptionPane.showMessageDialog(null, "Registrado sin comentarios para instalar el " + date.trim());

                                            Inicio ins = new Inicio();
                                            ins.setVisible(true);
                                            this.dispose();

                                        } else {
                                            pst.setString(1, "0");
                                            pst.setString(2, DIRECCION.getText().trim());
                                            pst.setString(3, CELULAR.getText().trim());
                                            pst.setString(4, CC.getText().trim());
                                            pst.setString(5, "PENDIENTE");
                                            pst.setString(6, NOMBRE.getText().trim());
                                            pst.setString(7, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                            pst.setString(8, valid.Devolver(date.trim()));
                                            pst.setString(9, zonasV[zonas.getSelectedIndex()]);
                                            info = consul.devolverU(IniciarSession.Username, "todos");
                                            pst.setString(10, info[4]);
                                            pst.setString(11, "0");
                                            pst.setString(12, "1000-01-01");
                                            pst.setString(13, precio.getText().trim());
                                            pst.setString(14, fechaa);

                                            pst1.setString(1, "0");
                                            pst1.setString(2, "000000");
                                            pst1.setString(3, fechaA.toString());//CAMBIAR
                                            pst1.setString(4, "0000-00-00");
                                            pst1.setString(5, "0");
                                            pst1.setString(6, DIRECCION.getText().trim());
                                            pst1.setString(7, "");
                                            pst1.setString(8, CELULAR.getText().trim());
                                            pst1.setString(9, "0");
                                            pst1.setString(10, "");
                                            pst1.setString(11, CC.getText().trim());
                                            pst1.setString(12, "PENDIENTE");
                                            pst1.setString(13, NOMBRE.getText().trim());
                                            pst1.setString(14, COMENT.getText().trim() + "\ntipo: " + jComboBox1.getSelectedItem().toString());
                                            pst1.setString(15, valid.Devolver(date.trim()));
                                            pst1.setString(16, zonasV[zonas.getSelectedIndex()]);
                                            pst1.setString(17, "");
                                            pst1.setString(18, info[4]);
                                            pst1.setString(19, "");
                                            pst1.setString(20, "");
                                            pst1.setString(21, "");
                                            pst1.setString(22, "");
                                            pst1.setString(23, "");

                                            pst1.execute();
                                            pst.execute();
                                            JOptionPane.showMessageDialog(null, "Registrado para instalar el " + date.trim());

                                            Inicio ins = new Inicio();
                                            ins.setVisible(true);
                                            this.dispose();

                                        }

                                    }
                                }
                            }
                        }
                    }
                }

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "servidor desconectado, intente reiniciar la conexion" + e);

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (editado == false) {

            this.dispose();
        } else {

            ConsultarAgenda.consul = false;
            this.dispose();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void zonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonasActionPerformed

    }//GEN-LAST:event_zonasActionPerformed

    private void Nombre_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt5ActionPerformed

    private void Nombre_txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Azona.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(null, "ingrese un nombre de zona antes de agregar");
        } else {
            if (idZona.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(null, "ingrese un id de zona antes de agregar, en su defecto escriba un 0 y se agregara automaticamente");
            } else {
                try {
                    Integer.parseInt(idZona.getText().trim());
                    try {
                        PreparedStatement pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("insert into zonas values(?,?)");
                        pst.setString(1, Azona.getText().trim());
                        pst.setString(2, idZona.getText().trim());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "zona agregada");
                        this.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "error: " + e);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "el id solo puede contener numeros");
                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void Nombre_txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt7ActionPerformed

    private void Nombre_txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt8ActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarActa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASIGNADO;
    private javax.swing.JTextField Azona;
    private javax.swing.JTextField CC;
    private javax.swing.JTextField CELULAR;
    private javax.swing.JTextPane COMENT;
    private com.toedter.calendar.JDateChooser DATE;
    private javax.swing.JTextField DIRECCION;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField Nombre_txt1;
    private javax.swing.JTextField Nombre_txt2;
    private javax.swing.JTextField Nombre_txt3;
    private javax.swing.JTextField Nombre_txt4;
    private javax.swing.JTextField Nombre_txt5;
    private javax.swing.JTextField Nombre_txt6;
    private javax.swing.JTextField Nombre_txt7;
    private javax.swing.JTextField Nombre_txt8;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel User;
    private javax.swing.JTextField idZona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox<String> zonas;
    // End of variables declaration//GEN-END:variables
}
