/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        setLocationRelativeTo(this);
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        Nick = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(423, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 74, 253, -1));
        getContentPane().add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 253, -1));
        getContentPane().add(Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 253, -1));
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 259, 253, -1));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 77, -1, -1));

        jLabel2.setText("correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 135, -1, -1));

        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 262, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Resgistrarme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 380, 152, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 421, 100, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 255));
        jTextField6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("  REGISTRO DE USUARIO");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 13, 152, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "oficina", "tecnico"}));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabel5.setText("privilegio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultarNombrePermiso consultar = new consultarNombrePermiso();
        consultarNickPas contraseña = new consultarNickPas();
        boolean info;
        int cedula;
        info = consultar.devolver(Nick.getText().trim());

        if (!info && Nick.getText().trim().length() > 1) {
            if (Nombre.getText().length() > 10) {
                if (CC.getText().length() >= 9) {
                    try {

                        if (Contrasena.getText().length() >= 8) {
                            try {

                                
                                PreparedStatement pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("insert into login values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                                pst.setString(1, "0");
                                pst.setString(2, Nick.getText().trim());
                                pst.setString(3, contraseña.getMD5(Contrasena.getText().toString().trim()));
                                switch (combo.getSelectedItem().toString().trim()) {
                                    case "admin":
                                        pst.setString(4, "0");
                                        break;
                                    case "oficina":
                                        pst.setString(4, "1");
                                        break;
                                    case "tecnico":
                                        pst.setString(4, "2");
                                        break;

                                }

                                pst.setString(5, Nombre.getText().trim());
                                pst.setString(6, "%%");
                                pst.setString(7, CC.getText().toString().trim());
                                pst.setString(8, "");
                                pst.setString(9, "1");
                                pst.setString(10, "habilitado");
                                pst.setString(11, "hombre_soporte.png");
                                pst.setString(12, "0");
                                pst.setString(13, "1");
                                pst.setString(14, "0");
                                pst.setString(15, "0.00");

                                pst.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Usuario Registrado como " + combo.getSelectedItem().toString().trim());
                                admin inst = new admin();
                                inst.setVisible(true);
                                this.dispose();

                            } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null, "algo salio mal " + e);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "la contraseña debe contener 8 mas caracteres");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "el numero de cedula solo puede contener numeros");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "ingrese un Numero de cedula");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ingrese un Nombre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "el nick ya existe");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        admin inst = new admin();
        inst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CC;
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField Nick;
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
