/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public EditarUsuario() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        String[] datos = new String[4];
        setLocationRelativeTo(this);
        String usuario = usuarios.username;
        consultar consultar1 = new consultar();
        datos = consultar1.devolverU(usuario, "todos");
        Nombre.setText(datos[0]);
        combo.setSelectedIndex(Integer.parseInt(datos[2]));
        correo.setText(datos[1]);
        username.setText(datos[3]);

    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 74, 253, -1));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 253, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 253, -1));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 77, -1, -1));

        jLabel2.setText("correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 135, -1, -1));

        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 380, 152, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 421, 100, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 255));
        jTextField6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("  REGISTRO DE USUARIO");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 13, 152, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "oficina", "tecnico"}));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabel5.setText("privilegio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultarNombrePermiso consultar = new consultarNombrePermiso();
        boolean info;
        int cedula;
        info = consultar.devolver(username.getText().trim());

        if ((!info && username.getText().trim().length() > 1) || username.getText().trim().equals(usuarios.username)) {
            if (Nombre.getText().length() > 10) {
                if (correo.getText().length() >= 9) {
                    try {

                        try {

                            
                            PreparedStatement pst = mantenerConexion.conectando.getconec1().getcn().prepareStatement("update login set username = ?, privilege = ?,nombre = ?, correo = ? WHERE username = ? ");
                            pst.setString(1, username.getText().trim());
                            pst.setString(4, correo.getText().trim());
                            switch (combo.getSelectedItem().toString().trim()) {
                                case "admin":
                                    pst.setString(2, "0");
                                    break;
                                case "oficina":
                                    pst.setString(2, "1");
                                    break;
                                case "tecnico":
                                    pst.setString(2, "2");
                                    break;

                            }

                            pst.setString(3, Nombre.getText().trim());
                            pst.setString(5, usuarios.username);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Usuario actualizado");

                            this.dispose();

                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "algo salio mal");
                        }

                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "el numero de cedula solo puede contener numeros");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "ingrese un Numero de cedula");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ingrese un Nombre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "el username ya existe");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
