/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.*;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author fvr
 */
public class VerEjecutadas extends javax.swing.JFrame {

    
    String[] datosReturn = new String[9];
    String[] datosReturn1 = new String[5];

    /**
     * Creates new form AgregarActa
     */
    public VerEjecutadas() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Fututel");
        
        DATE.setPreferredSize(new java.awt.Dimension(97, 22));

        String consultarB = AgendasRealizadas.id;

        consultar consultar1 = new consultar();
        datosReturn = consultar1.devolver(consultarB, AgendasRealizadas.tipo, "");

        DATE.setText(datosReturn[2]);
        NOMBRE.setText(datosReturn[5]);
        CC.setText(datosReturn[1]);
        COMENT.setText(datosReturn[0]);
        datosReturn1 = consultar1.devolverU(datosReturn[7]);
        User.setText(datosReturn1[0]);
        ASIGNADO.setText(datosReturn[8]);

        ZONA.setText(consultar1.devolver(datosReturn[3]));

        //aqui va el usuariooooo
        setLocationRelativeTo(this);

    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/fututel-icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        Nombre_txt = new javax.swing.JTextField();
        Nombre_txt1 = new javax.swing.JTextField();
        Nombre_txt4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        COMENT = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        User = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        ASIGNADO = new javax.swing.JLabel();
        DATE = new javax.swing.JTextField();
        ZONA = new javax.swing.JTextField();
        REGRESAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 704, 550));
        setMinimumSize(new java.awt.Dimension(705, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setEditable(false);
        Titulo.setBackground(new java.awt.Color(0, 153, 0));
        Titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText(" DATOS DE EJECUCION");
        Titulo.setBorder(null);
        Titulo.setName(""); // NOI18N
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 240, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("         FECHA DE EJECUCION");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 132, 215, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 153, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(240, 240, 240));
        jTextField2.setText("                                              DATOS DEL CLIENTE TITULAR");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 173, 596, -1));

        CC.setEditable(false);
        CC.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CCMouseClicked(evt);
            }
        });
        getContentPane().add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 376, -1));

        Nombre_txt.setEditable(false);
        Nombre_txt.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt.setText("              Nombre Del Cliente:");
        Nombre_txt.setToolTipText("");
        Nombre_txt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 201, 213, -1));

        Nombre_txt1.setEditable(false);
        Nombre_txt1.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt1.setText("                   Tipo De Agenda:");
        Nombre_txt1.setToolTipText("");
        Nombre_txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 213, -1));

        Nombre_txt4.setEditable(false);
        Nombre_txt4.setBackground(new java.awt.Color(153, 153, 153));
        Nombre_txt4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Nombre_txt4.setText("  Zona:");
        Nombre_txt4.setToolTipText("");
        Nombre_txt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nombre_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_txt4ActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 80, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(240, 240, 240));
        jTextField3.setText("                    EJECUTADO POR:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 215, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 528, -1, -1));

        COMENT.setEditable(false);
        jScrollPane3.setViewportView(COMENT);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 590, 76));

        jLabel1.setText("comentarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        NOMBRE.setEditable(false);
        NOMBRE.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        NOMBRE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NOMBRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOMBREMouseClicked(evt);
            }
        });
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 376, -1));

        User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        User.setText("agend user");
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 223, 20));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 153, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(240, 240, 240));
        jTextField4.setText("                     AGENDADO POR:");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 215, -1));
        getContentPane().add(ASIGNADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 180, 20));

        DATE.setEditable(false);
        DATE.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        DATE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DATEMouseClicked(evt);
            }
        });
        getContentPane().add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 133, 190, -1));

        ZONA.setEditable(false);
        ZONA.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ZONA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ZONA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZONAMouseClicked(evt);
            }
        });
        getContentPane().add(ZONA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 150, -1));

        REGRESAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        REGRESAR.setText("REGRESAR");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(REGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Nombre_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt1ActionPerformed

    private void Nombre_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txt4ActionPerformed

    private void CCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCMouseClicked


    }//GEN-LAST:event_CCMouseClicked

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void NOMBREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOMBREMouseClicked

    }//GEN-LAST:event_NOMBREMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void DATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DATEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DATEMouseClicked

    private void ZONAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZONAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ZONAMouseClicked

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        this.dispose();
    }//GEN-LAST:event_REGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEjecutadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ASIGNADO;
    private javax.swing.JTextField CC;
    private javax.swing.JTextPane COMENT;
    private javax.swing.JTextField DATE;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField Nombre_txt1;
    private javax.swing.JTextField Nombre_txt4;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel User;
    private javax.swing.JTextField ZONA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
